// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4vO-ujKegPocNwkT3j2wZVjVHyGd2JE',
    appId: '1:705918919478:web:cdca670e43d4d29d848997',
    messagingSenderId: '705918919478',
    projectId: 'flutter-chat-app-bf658',
    authDomain: 'flutter-chat-app-bf658.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bf658.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlbeiG-j_YYYxXyN1JfISU_-7RC0ZTB8Y',
    appId: '1:705918919478:android:4a3aac246add1943848997',
    messagingSenderId: '705918919478',
    projectId: 'flutter-chat-app-bf658',
    storageBucket: 'flutter-chat-app-bf658.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJSeeyEggaejpkLPoUEQCGmf9cRDXAoS8',
    appId: '1:705918919478:ios:251f6fff80d993f5848997',
    messagingSenderId: '705918919478',
    projectId: 'flutter-chat-app-bf658',
    storageBucket: 'flutter-chat-app-bf658.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJSeeyEggaejpkLPoUEQCGmf9cRDXAoS8',
    appId: '1:705918919478:ios:251f6fff80d993f5848997',
    messagingSenderId: '705918919478',
    projectId: 'flutter-chat-app-bf658',
    storageBucket: 'flutter-chat-app-bf658.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4vO-ujKegPocNwkT3j2wZVjVHyGd2JE',
    appId: '1:705918919478:web:2e7475992c11d482848997',
    messagingSenderId: '705918919478',
    projectId: 'flutter-chat-app-bf658',
    authDomain: 'flutter-chat-app-bf658.firebaseapp.com',
    storageBucket: 'flutter-chat-app-bf658.appspot.com',
  );

}